# Use tinnova/tinnova123 user/password credentials
version: '3.1'

services:   
  app:
    image: prajinults/swift-shop-gen-ai-fr
    ports:
      - 8080:8080
    environment:
      DB_HOST: 172.27.224.5
      DB_PWD: ZOHrztvnYYsW7hz