services:
  coturn_server:
    image: coturn/coturn:4.5.2
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
      - ./etc/letsencrypt:/etc/letsencrypt
  app:
    image: prajinults/swift-shop-gen-ai-fr:latest-gpu
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_PWD: password
      DB_USER: postgres
      GPU_ENABLED: 0
      COOKIE_SECURE: 0
      COOKIE_HTTP_ONLY: 0
      THRESHOLD: 0.6
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]  
  db:
    image: google/alloydbomni
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
  nginx:
    image: bitnami/nginx:1.25.5
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./app:/app
      - ./nginx.conf:/opt/bitnami/nginx/conf/nginx.conf
      - ./server_blocks:/opt/bitnami/nginx/conf/server_blocks/
      - ./etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
      - coturn_server
      - db
volumes:
  db_data:
    driver: local    